# permissions to do edit nginxapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nginxapp-editor-role
rules:
- apiGroups:
  - apps.example.com
  resources:
  - nginxapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.example.com
  resources:
  - nginxapps/status
  verbs:
  - get
  - patch
  - update
