# permissions to do viewer nginxapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nginxapp-viewer-role
rules:
- apiGroups:
  - apps.example.com
  resources:
  - nginxapps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.example.com
  resources:
  - nginxapps/status
  verbs:
  - get
