
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: nginxapps.apps.example.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Phase
    type: string
  - JSONPath: .metadata.creationTimestamp
    name: Age
    type: date
  group: apps.example.com
  names:
    kind: NginxApp
    plural: nginxapps
    shortNames:
    - napp
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: NginxApp is the Schema for the nginxapps API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: NginxAppSpec defines the desired state of NginxApp
          properties:
            helperapp:
              properties:
                image:
                  type: string
                welcometext:
                  type: string
              required:
              - image
              - welcometext
              type: object
            mainapp:
              properties:
                image:
                  type: string
                welcometext:
                  type: string
              required:
              - image
              - welcometext
              type: object
          required:
          - helperapp
          - mainapp
          type: object
        status:
          description: NginxAppStatus defines the observed state of NginxApp
          properties:
            phase:
              enum:
              - Pending
              - Running
              - Failed
              type: string
          required:
          - phase
          type: object
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
